name: sdss2025
channels:
  - conda-forge
dependencies:
  - python
  - bokeh>=3.7.2,<4
  - clustergram>=0.8.1,<0.9
  - geopandas>=1.0.1,<2
  - geopy>=2.4.1,<3
  - ipywidgets>=8.1.6,<9
  - jupyterlab>=4.4.0,<5
  - momepy>=0.10.0
  - neatnet>=0.1.0
  - numba>=0.61.2,<0.62
  - osmnx>=2.0.2,<3
  - scikit-learn>=1.6.1,<2
  - shapely>=2.1.0,<3
  - pip
  - pip:
      - geoplanar
